<a href="https://colab.research.google.com/github/yesol-park1/PYTHON/blob/main/11%EC%A3%BC%EC%B0%A8_%EC%88%99%EC%A0%9C_2026173655_%EB%B0%95%EC%98%88%EC%86%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 11주차 과제: NumPy 기초

NumPy 공식 문서의 "NumPy: the absolute basics for beginners" 예제 코드를 따라 작성하고 실행한 결과입니다.

범위:
- How to import NumPy
- Array fundamentals
- Array attributes
- How to create a basic array
- Adding, removing, and sorting elements
- Shape and size of an array
- Reshape
- newaxis, expand_dims
- Indexing and slicing
- Creating arrays from existing data
- Basic array operations
- Broadcasting
- More useful array operations
- Creating matrices
- Random numbers
- Unique items and counts
- Transposing and reshaping a matrix
- Reverse array
- Reshaping and flattening multidimensional arrays

In [5]:
import numpy as np

In [6]:
# Array fundamentals

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

print(a[0])

a[0] = 10
print(a)

print(a[:3])

b = a[3:]
print(b)

b[0] = 40
print(a)

[1 2 3 4 5 6]
1
[10  2  3  4  5  6]
[10  2  3]
[4 5 6]
[10  2  3 40  5  6]


In [7]:
# 2차원 배열

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(a)
print(a[1, 3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
8


In [8]:
# Array attributes

print(a.ndim)
print(a.shape)

import math
print(a.size)
print(a.size == math.prod(a.shape))

print(a.dtype)

2
(3, 4)
12
True
int64


In [9]:
# How to create a basic array

print(np.zeros(2))
print(np.ones(2))
print(np.empty(2))

print(np.arange(4))
print(np.arange(2, 9, 2))
print(np.linspace(0, 10, num=5))

x = np.ones(2, dtype=np.int64)
print(x)

[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[1 1]


In [10]:
# Adding, removing, and sorting elements

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(np.concatenate((a, b)))

x = np.array([[1, 2],
              [3, 4]])

y = np.array([[5, 6]])

print(np.concatenate((x, y), axis=0))

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]]


In [11]:
# Shape and size

array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example.ndim)
print(array_example.size)
print(array_example.shape)

3
24
(3, 2, 4)


In [12]:
# Reshape

a = np.arange(6)
print(a)

b = a.reshape(3, 2)
print(b)

print(np.reshape(a, newshape=(1, 6), order='C'))

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3 4 5]]


In [13]:
# np.newaxis, np.expand_dims

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)

a2 = a[np.newaxis, :]
print(a2.shape)
print(a2)

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

b = np.expand_dims(a, axis=1)
print(b.shape)
print(b)

c = np.expand_dims(a, axis=0)
print(c.shape)
print(c)

(6,)
(1, 6)
[[1 2 3 4 5 6]]
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(1, 6)
[[1 2 3 4 5 6]]


In [14]:
# Indexing and slicing

data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(a[a < 5])

five_up = (a >= 5)
print(a[five_up])

divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)

c = a[(a > 2) & (a < 11)]
print(c)

five_up = (a > 5) | (a == 5)
print(five_up)

2
[1 2]
[2 3]
[2 3]
[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [15]:
# np.nonzero

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = np.nonzero(a < 5)
print(b)

list_of_coordinates = list(zip(b[0], b[1]))
print(list_of_coordinates)

for coord in list_of_coordinates:
    print(coord)

print(a[b])

not_there = np.nonzero(a == 42)
print(not_there)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
[(np.int64(0), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(3))]
(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))
[1 2 3 4]
(array([], dtype=int64), array([], dtype=int64))


In [16]:
# How to create an array from existing data

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr1 = a[3:8]
print(arr1)

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

print(np.vstack((a1, a2)))
print(np.hstack((a1, a2)))

x = np.arange(1, 25).reshape(2, 12)
print(x)

print(np.hsplit(x, 3))
print(np.hsplit(x, (3, 4)))

[4 5 6 7 8]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [17]:
# View and Copy

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b1 = a[0, :]
print(b1)

b1[0] = 99
print(b1)
print(a)

b2 = a.copy()
print(b2)

b2[0, 0] = 100
print(b2)
print(a)

[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# Basic array operations

data = np.array([1, 2])
ones = np.ones(2, dtype=int)

print(data + ones)
print(data - ones)
print(data * data)
print(data / data)

a = np.array([1, 2, 3, 4])
print(a.sum())

[2 3]
[0 1]
[1 4]
[1. 1.]
10


In [19]:
# 2D array operations

b = np.array([[1, 1],
              [2, 2]])

print(b.sum(axis=0))
print(b.sum(axis=1))

[3 3]
[2 4]


In [20]:
# Broadcasting

data = np.array([1.0, 2.0])
print(data * 1.6)

[1.6 3.2]


In [21]:
# More useful array operations

data = np.array([1.0, 2.0])

print(data.max())
print(data.min())
print(data.sum())

a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(a.sum())
print(a.min())
print(a.min(axis=0))

2.0
1.0
3.0
4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]


In [22]:
# Creating matrices

data = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

print(data)
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

print(data.max())
print(data.min())
print(data.sum())

print(data.max(axis=0))
print(data.max(axis=1))

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]
6
1
21
[5 6]
[2 4 6]


In [23]:
# Matrix operations

data = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

ones = np.array([[1, 1],
                 [1, 1],
                 [1, 1]])

print(data + ones)

ones_row = np.array([[1, 1]])
print(data + ones_row)

[[2 3]
 [4 5]
 [6 7]]
[[2 3]
 [4 5]
 [6 7]]


In [24]:
# Generating random numbers

rng = np.random.default_rng()

print(rng.random(3))
print(rng.random((3, 2)))

print(rng.integers(5, size=(2, 4)))

[0.75830334 0.48273212 0.60038112]
[[0.40266295 0.67431517]
 [0.21214404 0.85366716]
 [0.14839736 0.64257473]]
[[0 0 3 4]
 [4 4 1 2]]


In [25]:
# Unique items and counts

a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)
print(unique_values)

unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]


In [26]:
# Unique with 2D array

a_2d = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [1, 2, 3, 4]])

unique_values = np.unique(a_2d)
print(unique_values)

unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True
)

print(unique_rows)
print(indices)
print(occurrence_count)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [27]:
# Transposing and reshaping a matrix

data = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

print(data.reshape(2, 3))
print(data.reshape(3, 2))

arr = np.arange(6).reshape((2, 3))
print(arr)

print(arr.transpose())
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


In [28]:
# How to reverse an array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)

print(reversed_arr)

arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

reversed_arr = np.flip(arr_2d)
print(reversed_arr)

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

arr_2d[:, 1] = np.flip(arr_2d[:, 1])
print(arr_2d)

[8 7 6 5 4 3 2 1]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [29]:
# Reshaping and flattening multidimensional arrays

x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(x.flatten())

a1 = x.flatten()
a1[0] = 99

print(x)
print(a1)

a2 = x.ravel()
a2[0] = 98

print(x)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]
[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
